from app import db

from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = ...
    username = ...
    email = ...
    pasword_hash = ...
    is_active = ...

    def __str__(self):
        return self.username