"""migracion inicial

Revision ID: 35bd5fcabf1e
Revises: 
Create Date: 2025-08-05 17:54:25.527308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35bd5fcabf1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.drop_column('passeword_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passeword_hash', mysql.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
